"""Initial schema: games, tags, genres, categories, and the vector column.

Hand-written rather than autogenerated: alembic does not render pgvector's
Vector type or generated columns reliably, and this is the file every later
query silently depends on.

The HNSW index on games.embedding is NOT created here. Building it before the
rows exist means rewiring the graph 130k times during ingest. It arrives in a
separate migration, run after the embed job.

Revision ID: 0001
Revises:
Create Date: 2026-08-20

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Must match EMBEDDING_DIM in app/models.py. nomic-embed-text emits 768;
# Weekend 3's bge-m3 emits 1024 and will need its own migration.
EMBEDDING_DIM = 768


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "games",
        # Steam's app_id. Max observed is 5,074,790 — comfortably inside int4.
        sa.Column("app_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("detailed_description", sa.Text(), nullable=True),
        # Source is 'Mon D, YYYY' for 100% of rows, so this parses without a
        # fallback path.
        sa.Column("release_date", sa.Date(), nullable=True),
        # US storefront prices. price_eur is added in Weekend 3 from the
        # storefront API with ?cc=de. Do not filter euros against this column.
        sa.Column("price_usd", sa.Numeric(10, 2), nullable=True),
        # Derived at ingest as (price == 0); the source has no is_free field.
        # 28,255 rows are price-0, some of which are unreleased rather than free.
        sa.Column(
            "is_free", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "windows", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("mac", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "linux", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "positive_reviews", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "negative_reviews", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        # Maintained by Postgres so the search filter is `total_reviews > :n`
        # rather than a sum recomputed per row per query.
        sa.Column(
            "total_reviews",
            sa.Integer(),
            sa.Computed("positive_reviews + negative_reviews", persisted=True),
            nullable=True,
        ),
        sa.Column("metacritic_score", sa.Integer(), nullable=True),
        sa.Column("estimated_owners", sa.Text(), nullable=True),
        sa.Column("header_image", sa.Text(), nullable=True),
        sa.Column("developers", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("publishers", sa.ARRAY(sa.Text()), nullable=True),
        # The exact string sent to the embedding model, kept so a surprising
        # result can be traced to what was actually embedded.
        sa.Column("embed_text", sa.Text(), nullable=True),
        # NULL means "not embedded yet" — this is what makes the embed job
        # resumable across interruptions.
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("app_id"),
    )
    op.create_index("ix_games_price_usd", "games", ["price_usd"])
    op.create_index("ix_games_release_date", "games", ["release_date"])
    op.create_index("ix_games_total_reviews", "games", ["total_reviews"])
    # Partial index: the embed job repeatedly asks "what is left?", and this
    # keeps that cheap as the unembedded set shrinks toward zero.
    op.create_index(
        "ix_games_unembedded",
        "games",
        ["app_id"],
        postgresql_where=sa.text("embedding IS NULL"),
    )

    # 1,180,522 rows. Normalised rather than an array because votes are what
    # "top 15 tags by votes" ranks on, and an array column cannot carry them.
    op.create_table(
        "game_tags",
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.Text(), nullable=False),
        sa.Column("votes", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("app_id", "tag"),
    )
    op.create_index("ix_game_tags_tag", "game_tags", ["tag"])
    # Serves "top 15 tags by votes for this game": Postgres scans a btree
    # backwards as readily as forwards, so no explicit DESC is needed.
    op.create_index("ix_game_tags_app_votes", "game_tags", ["app_id", "votes"])

    op.create_table(
        "game_genres",
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("genre", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("app_id", "genre"),
    )
    op.create_index("ix_game_genres_genre", "game_genres", ["genre"])

    # Steam's own categories ('Multi-player', 'Co-op'). Weekend 2's multiplayer
    # filter reads these — more reliable for that than community tags.
    op.create_table(
        "game_categories",
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("app_id", "category"),
    )
    op.create_index("ix_game_categories_category", "game_categories", ["category"])


def downgrade() -> None:
    # Child tables first: the FKs point at games.app_id.
    op.drop_table("game_categories")
    op.drop_table("game_genres")
    op.drop_table("game_tags")
    op.drop_table("games")
    # The extension is deliberately left installed. Dropping it would break any
    # other database in this cluster using vector columns, and re-creating it
    # is free.
